### PR TITLE
Y-axis-precision-rounding

### LINKED ISSUE #91: y-axis ticks: inappropriate values displayed for some data series
https://www.figurl.org/f?v=gs://figurl/spikesortingview-8&d=sha1://c9ae9a07468d6f55cf5b6713bb068554247e749d&label=test_spike_amplitudes&s={}

Select units 0 and 6, zoom in (via wheel) a few times on 1 min 20 s. Note that some minor y-axis ticks are displaying incorrectly as large 0-prefixed numbers, e.g. `000001` instead of `0.6`. Suspect a rounding error or similar--investigate this.

### PR DESCRIPTION
**Pull request by magland**
Fixes #91

### CODE REVIEW

File: src/libraries/component-time-scroll-view/YAxisTicks.ts [hunk 1]
```diff
@@ -69,12 +71,12 @@ const makeStep = (raw: number, base: number, scale: number): Step => {
     const trimmed = raw - (TRUNCATE_UNCHANGED_HIGHER_ORDER_DIGITS ? base : 0)
     const scaled = Math.trunc(trimmed * Math.pow(10, -scale))
     const isMajor = scaled % 10 === 0
-    const label =  Math.abs(scale) > 3 ? `${(scaled/10).toFixed(1)}e${scale + 1}` : `${scaled * Math.pow(10, scale)}`
+    const label =  Math.abs(scale) > 3 ? `${(scaled/10).toFixed(1)}e${scale + 1}` : `${Math.round(scaled * Math.pow(10, scale) * 1e9) / 1e9}` // use precision rounding
```
Comment (jsoules) [inline src/libraries/component-time-scroll-view/YAxisTicks.ts:74]: I would've hoped the truncation above would take care of this... oh well, guess not :(

Seems a good fix!
